### ISSUE TITLE
Search company, unable to figure out Request data

### ISSUE THREAD

**Issue by Engazan** [Foxentry/PHP-LIB#3]
Hi i would like to know how can i figure out what i need to send to `Search company` endpoint -> https://foxentry.dev/reference/companysearch

cuz i cant find any request params and sadly `/src/Resource/Company.php` function `search` has `array` as param :/, is there any DTO ? or maybe documentation that describe what i need to send ? 

i see `$query` is sent to request body so where i can figure out all combinations from that example in docs ? ( maybe i missed something but cant figure it out by my own ) 

![image](https://github.com/Foxentry/PHP-LIB/assets/53254371/b2350f7d-a62b-40e2-b072-f6ae2dc43e5f)

for example if i want to search by registrationNumber ? but doc for this will be great, thanks

what i tryed so far
```php
try {
            $apiClient = self::getApiClient();
            $response = $apiClient
                ->company
                ->setOptions([
                    'dataScope' => 'extended',
                    'resultsLimit' => 1,
                ])
                ->search([
                    'type' => 'registrationNumber',
                    'filter' => [
                        'country' => $country2Code,
                    ],
                    'value' => $registrationNumber, // searched value
                ]);
        } catch (\Exception $e) {
            dd($e->getMessage());
        }

        dd($response);
        ```
     
it worked but i kind of miss maybe more info what i can send

**Comment by dominikhosic** [comment]
Hello, Engazan,

on [Foxentry.dev](https://foxentry.dev/reference/companysearch) in the Response section, there are example responses that can give you ideas about what is possible.

![image](https://github.com/Foxentry/PHP-LIB/assets/143003738/f55cb2dd-035f-4922-b06e-4e9cd469adc1)

Additionally, by expanding the request object, you can see all the possible inputs and options with descriptions. You can also make API calls directly from Foxentry.dev and see if the API returns your expected result.
![image](https://github.com/Foxentry/PHP-LIB/assets/143003738/d303e434-686b-4ad5-a509-0b4f18e2761b)
